[package]
name = "led-strip"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[dependencies]
esp-idf-sys = {git = "https://github.com/ivmarkov/esp-idf-sys.git"}
thiserror = "1.0.22"
